name: winpython
channels:
- defaults
- conda-forge
dependencies:
- python==3.6.3
- numpy==1.13.3
- bokeh==0.12.10
- ipython==6.2.1
- nbformat==4.4.0
- jupyter=1.0.0
- pandas==0.21
- notebook==5.2.1
- ipywidgets==7.0.3
- python-dateutil==2.6.1
- scikit-learn==0.19.1
- matplotlib==2.1.0
- seaborn==0.8.1